version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - .:/usr/src/app
  db:
    image: mongo
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
