INSERT INTO USUARIO (USER, CONTRASENA, ENABLED)
VALUES
	('pepe', '$2a$04$Xl15KN5O4Q4R7zAescf8y.tSCDEUy.l.IGMazJ/8RC2e71SuFgw/e', TRUE);

INSERT INTO USUARIO (USER, CONTRASENA, ENABLED)
VALUES
	('admin', '$2a$04$dJ5YWbG5dE0wuPaPZWQDHu2oM/K2luEFhxsztxM6jhNsaU4iT8lvO', TRUE);

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES
	('admin', 'ROLE_ADMIN');

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES
	('pepe', 'ROLE_USER');